# Generated by Django 3.2.7 on 2021-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutella', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.URLField(default=''),
        ),
    ]
